name: Build without DB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt update && sudo apt install -y libcgicc-dev libcurl4-openssl-dev
    - name: make
      run: DONT_COMPRESS_OUTPUT=1 DISABLE_MYSQL=true make
