name: Build without DB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install -y libcgicc-dev libcurl4-openssl-dev
    - name: DISABLE_MYSQL=true make
      run: make
