name: Build on ubuntu-latest

on:
  push:
    branches: [ "main" ]
    paths:
      - ./**/*.cpp
      - ./**/*.c
      - ./**/*.hpp
      - ./**/*.h
      - ./**/*.cpphtml
      - ./**/Makefile
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install -y libcgicc-dev libcurl4-openssl-dev
    - name: make
      run: make
