name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install cgicc
      run: sudo apt install -y libcgicc-dev libcurl-dev
    - name: make
      run: make
